--- # EC2 MODULE PROVISIONING EXAMPLE
- hosts: local
  connection: local
  remote_user: ec2-user
  become: yes
  gather_facts: no
  vars_files:
  - /File Path####
  tasks:
  - name: Basic provisioning of two t2.micro instances
    ec2:
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      region: "{{ aws_region }}"
      image: ami-#####
      instance_type: t2.micro
      count: 2
     
