--- # EC2 MODULE PROVISIONING EXAMPLE
- hosts: localhost
  connection: local
  remote_user: ec2-user
  become: yes
  gather_facts: no
  var_files:
  - files/keys.yml
  tasks:
  - name: Basic provisioning of two t2.micro instances
  ec2:
     aws_access_key: "{{aws_id}}"
     aws_secret_key: "{{aws_key}}"
     image: ami-f0091d91
     instance_type: t2.micro
     count: 2
     
