--- # Gathwer EC2 Facts from my remote instance
- hosts: aws
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks: 
  - name: Gather the ec2 facts about running instances
    action: ec2_fatcs
  - name: onditional display of instance type
    debug: msg="This Instance is of type t2.micro"
    when: ansible_ec2_instance_type == 't2.micro'        
